import type { Strategy, Trade } from "./types";

export const seedStrategy: Strategy = {
  name: "1H Fair Value Gap Continuation",
  version: "1.1",
  summary:
    "ICT / Smart Money continuation system. Daily/4H bias → 4H POI → liquidity sweep + 1H displacement → enter the 1H FVG at CE. Rules-based, not discretionary vibes.",
  edge:
    "Trade only 1H FVGs that form after a liquidity sweep + displacement, aligned with Daily/4H structure, in the correct premium/discount zone, during London or New York.",
  timeframes: [
    { role: "Macro", tf: "Weekly", job: "Major structure + weekly open / key levels" },
    { role: "Bias", tf: "Daily", job: "Direction for the day/week via swings + BOS" },
    { role: "Zone", tf: "4H", job: "Whitelist POI only: FVG, Order Block, or overlap" },
    { role: "Entry", tf: "1H", job: "FVG after sweep + displacement; enter at CE" },
  ],
  rules: [
    {
      title: "Daily bias",
      body: "Bullish needs HH + HL + bullish BOS. Bearish needs LH + LL + bearish BOS. Mixed structure = no trade.",
    },
    {
      title: "Premium / Discount",
      body: "Longs only from discount. Shorts only from premium. At EQ (±0.05%) = no trade.",
    },
    {
      title: "4H POI whitelist",
      body: "Only unmitigated 4H FVG, 4H Order Block, or overlap. No random S/R or trendlines.",
    },
    {
      title: "Liquidity sweep",
      body: "SSL sweep for longs / BSL sweep for shorts into the POI, then reclaim close within 6 one-hour candles.",
    },
    {
      title: "1H displacement + FVG",
      body: "C2 body ≥ 1.5× avg of prior 10 bodies, correct direction, creates valid FVG, and prints 1H MSS.",
    },
    {
      title: "Entry model",
      body: "Primary: limit at CE of the fresh/first-touch 1H FVG. Invalid if body closes through far edge.",
    },
  ],
  risk: [
    {
      title: "Risk per trade",
      body: "Risk a fixed R. Stop beyond invalidation of the FVG / sweep structure.",
    },
    {
      title: "Weekly volume",
      body: "Max 2–6 quality trades per week. Skip third-touch FVGs and revenge re-entries at the same POI.",
    },
    {
      title: "Drawdown soft stop",
      body: "Soft stop at −6R / month. If expectancy dies over 30+ closed trades, stop and review rules.",
    },
  ],
  targets: [
    { metric: "Win rate", value: "40–55%" },
    { metric: "Avg R:R", value: "≥ 1:2.0" },
    { metric: "Expectancy", value: "≥ +0.35R / trade" },
    { metric: "Max trades / week", value: "2–6" },
    { metric: "Max DD", value: "−6R / month soft stop" },
  ],
  approach:
    "Before every trade: lock Daily bias → confirm PD zone → wait for whitelist 4H POI → require sweep + 1H displacement + MSS → enter CE of the 1H FVG → manage to ≥2R or structure target. If any checklist item fails, stand down.",
  updatedAt: new Date().toISOString(),
};

const R = 100; // $ risked per 1R in seed book

export const seedTrades: Trade[] = [
  {
    id: "t1",
    date: "2026-07-01",
    symbol: "EURUSD",
    side: "long",
    setup: "1H FVG Continuation",
    entry: 1.1682,
    stop: 1.1658,
    target: 1.1730,
    exit: 1.1730,
    entryTime: "2026-07-01T08:42:00Z",
    exitTime: "2026-07-01T12:18:00Z",
    timeInTradeMinutes: 216,
    riskUsd: R,
    pnlUsd: 200,
    feesUsd: 2.4,
    size: "0.40 lots",
    rMultiple: 2.0,
    result: "win",
    notes: "London SSL sweep into 4H FVG, clean CE fill.",
    session: "London",
  },
  {
    id: "t2",
    date: "2026-07-03",
    symbol: "GBPUSD",
    side: "short",
    setup: "1H FVG Continuation",
    entry: 1.3524,
    stop: 1.3550,
    target: 1.3472,
    exit: 1.3550,
    entryTime: "2026-07-03T13:05:00Z",
    exitTime: "2026-07-03T13:41:00Z",
    timeInTradeMinutes: 36,
    riskUsd: R,
    pnlUsd: -100,
    feesUsd: 2.8,
    size: "0.35 lots",
    rMultiple: -1.0,
    result: "loss",
    notes: "Sweep was valid but NY news spiked through stop.",
    session: "New York",
  },
  {
    id: "t3",
    date: "2026-07-07",
    symbol: "XAUUSD",
    side: "long",
    setup: "1H FVG Continuation",
    entry: 2384.5,
    stop: 2376.0,
    target: 2401.5,
    exit: 2401.5,
    entryTime: "2026-07-07T09:12:00Z",
    exitTime: "2026-07-07T14:55:00Z",
    timeInTradeMinutes: 343,
    riskUsd: R,
    pnlUsd: 200,
    feesUsd: 3.1,
    size: "0.10 lots",
    rMultiple: 2.0,
    result: "win",
    notes: "4H OB + FVG overlap. Textbook displacement.",
    session: "London",
  },
  {
    id: "t4",
    date: "2026-07-09",
    symbol: "EURUSD",
    side: "short",
    setup: "IFVG",
    entry: 1.1748,
    stop: 1.1770,
    target: 1.1704,
    exit: 1.1710,
    entryTime: "2026-07-09T14:22:00Z",
    exitTime: "2026-07-09T16:48:00Z",
    timeInTradeMinutes: 146,
    riskUsd: R,
    pnlUsd: 170,
    feesUsd: 2.2,
    size: "0.45 lots",
    rMultiple: 1.7,
    result: "win",
    notes: "Inversion at Daily premium POI.",
    session: "New York",
  },
  {
    id: "t5",
    date: "2026-07-11",
    symbol: "USDJPY",
    side: "long",
    setup: "1H FVG Continuation",
    entry: 157.42,
    stop: 157.18,
    target: 157.90,
    exit: 157.18,
    entryTime: "2026-07-11T01:18:00Z",
    exitTime: "2026-07-11T03:02:00Z",
    timeInTradeMinutes: 104,
    riskUsd: R,
    pnlUsd: -100,
    feesUsd: 1.9,
    size: "0.25 lots",
    rMultiple: -1.0,
    result: "loss",
    notes: "Entered second touch — should have waited for fresh only.",
    session: "Asian",
  },
  {
    id: "t6",
    date: "2026-07-14",
    symbol: "NAS100",
    side: "long",
    setup: "1H FVG Continuation",
    entry: 20485,
    stop: 20420,
    target: 20615,
    exit: 20615,
    entryTime: "2026-07-14T13:35:00Z",
    exitTime: "2026-07-14T17:10:00Z",
    timeInTradeMinutes: 215,
    riskUsd: R,
    pnlUsd: 200,
    feesUsd: 4.5,
    size: "1 contract",
    rMultiple: 2.0,
    result: "win",
    notes: "NY open displacement after SSL sweep.",
    session: "New York",
  },
  {
    id: "t7",
    date: "2026-07-16",
    symbol: "GBPUSD",
    side: "long",
    setup: "1H FVG Continuation",
    entry: 1.3488,
    stop: 1.3462,
    target: 1.3540,
    exit: 1.3514,
    entryTime: "2026-07-16T07:50:00Z",
    exitTime: "2026-07-16T11:05:00Z",
    timeInTradeMinutes: 195,
    riskUsd: R,
    pnlUsd: 100,
    feesUsd: 2.6,
    size: "0.35 lots",
    rMultiple: 1.0,
    result: "win",
    notes: "Partial at 1R, closed remainder into London close.",
    session: "London",
  },
  {
    id: "t8",
    date: "2026-07-18",
    symbol: "EURUSD",
    side: "short",
    setup: "1H FVG Continuation",
    entry: 1.1712,
    stop: 1.1736,
    target: 1.1664,
    exit: 1.1664,
    entryTime: "2026-07-18T08:15:00Z",
    exitTime: "2026-07-18T13:40:00Z",
    timeInTradeMinutes: 325,
    riskUsd: R,
    pnlUsd: 200,
    feesUsd: 2.3,
    size: "0.40 lots",
    rMultiple: 2.0,
    result: "win",
    notes: "Daily LH/LL + premium 4H FVG.",
    session: "London",
  },
  {
    id: "t9",
    date: "2026-07-22",
    symbol: "XAUUSD",
    side: "short",
    setup: "1H FVG Continuation",
    entry: 2412.0,
    stop: 2420.5,
    target: 2395.0,
    exit: 2420.5,
    entryTime: "2026-07-22T14:08:00Z",
    exitTime: "2026-07-22T15:01:00Z",
    timeInTradeMinutes: 53,
    riskUsd: R,
    pnlUsd: -100,
    feesUsd: 3.0,
    size: "0.10 lots",
    rMultiple: -1.0,
    result: "loss",
    notes: "Bias was chop — broke own no-trade rule.",
    session: "New York",
  },
  {
    id: "t10",
    date: "2026-07-24",
    symbol: "EURUSD",
    side: "long",
    setup: "1H FVG Continuation",
    entry: 1.1620,
    stop: 1.1596,
    target: 1.1668,
    exit: 1.1668,
    entryTime: "2026-07-24T09:28:00Z",
    exitTime: "2026-07-24T15:12:00Z",
    timeInTradeMinutes: 344,
    riskUsd: R,
    pnlUsd: 200,
    feesUsd: 2.4,
    size: "0.40 lots",
    rMultiple: 2.0,
    result: "win",
    notes: "Best A+ of the month. Overlap POI + London sweep.",
    session: "London",
  },
  {
    id: "t11",
    date: "2026-07-27",
    symbol: "GBPUSD",
    side: "short",
    setup: "1H FVG Continuation",
    entry: 1.3560,
    stop: 1.3584,
    target: 1.3512,
    exit: undefined,
    entryTime: "2026-07-27T08:55:00Z",
    exitTime: undefined,
    riskUsd: R,
    pnlUsd: undefined,
    feesUsd: 1.2,
    size: "0.35 lots",
    rMultiple: 0,
    result: "open",
    notes: "Live — CE filled, targeting structure low.",
    session: "London",
  },
];
